### PR TITLE
metascraper-iframe: add twitter player iframe support

### LINKED ISSUE #478: Support Twitter:Player in metascraper-iframe
### Prerequisites

- [x] I'm using the last version.
- [x] My node version is the same as declared as `package.json`.

### Subject of the issue

Twitter's [Player Card spec](https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/player-card#:~:text=%C2%A0-,Reference,-Card%20Property) defines the content of the `twitter:player` tag as "HTTPS URL to iFrame player." If a website doesn't support oEmbed, it would be ideal if metascraper-iframe returned a useful response powered by the `twitter:player`, `twitter:player:width`, and `twitter:player:height` tags.

### Steps to reproduce

[RunKit Sample Code](https://runkit.com/nathangathright/metascraper-twitter-video)
```
const oEmbed = require('oembed-spec')
const metascraper = require("metascraper")([
  require("metascraper-url")(),
  require("metascraper-iframe")(),
]);
const got = require("got");

const targetUrl = 'https://share.transistor.fm/s/ddad295d';

exports.endpoint = async function(req, res) {
    const { body: html, url } = await got(targetUrl);
    const metadata = await metascraper({ html, url });
    res.send(JSON.stringify(metadata));
}
```

### Expected behaviour

```
{
  "url": "https://share.transistor.fm/s/ddad295d",
  "iframe": "<iframe src=\"https://share.transistor.fm/e/ddad295d\" height=\"180px\" width=\"500px\" frameborder=\"0\" scrolling=\"no\"></iframe>"
}
```

### Actual behaviour

```
{
  url: 'https://share.transistor.fm/s/ddad295d',
  iframe: null
}
```

### PR DESCRIPTION
**Pull request by Kikobeats**
closes #478

### CODE REVIEW

File: packages/metascraper-iframe/test/index.js [hunk 1]
```diff
@@ -60,6 +61,20 @@ describe('metascraper-iframe', () => {
...
+      const html = await readFile(
+        resolve(__dirname, 'fixtures/indiehacker.html')
+      )
+      const url = 'https://share.transistor.fm/s/ddad295d'
+      const rules = [createMetascraperIframe()]
+      const metascraper = createMetascraper(rules)
+      const meta = await metascraper({ url, html, iframe: { maxWidth: 350 } })
+
+      should(meta.iframe).be.equal(
+        '<iframe src="https://share.transistor.fm/e/ddad295d" frameborder="0" scrolling="no" maxWidth="350"></iframe>'
```
Comment (Kikobeats) [inline packages/metascraper-iframe/test/index.js:75]: @nathangathright that is what you wanted to achieve, right? 🙂

File: packages/metascraper-iframe/src/from-twitter.js [hunk 2]
```diff
@@ -0,0 +1,29 @@
...
+const { map } = require('lodash')
+
+const getPlayerUrl = memoizeOne(
+  (url, $) =>
+    normalizeUrl(
+      url,
+      $('meta[name="twitter:player"]').attr('content') ||
+        $('meta[property="twitter:player"]').attr('content') ||
+        $('meta[name="twitter:player:stream"]').attr('content') ||
+        $('meta[property="twitter:player:stream"]').attr('content')
```
Comment (Kikobeats) [inline packages/metascraper-iframe/src/from-twitter.js:13]: @nathangathright I added `twitter:player:stream` as well 👍

Comment (nathangathright) [reply packages/metascraper-iframe/src/from-twitter.js:13]: `twitter:player:stream` _should_ point to the MP3/MP3 file URL if available, so I don't think that's what you want to be inserted as the source for an iframe unless you add a contentType check. It's already being pulled into metascraper-audio and metascraper-video correctly.

In fact, the references to `twitter:player` in the [audio](https://github.com/microlinkhq/metascraper/blob/52d8598415802e92e10fcdffc4bc21aa28a640ea/packages/metascraper-audio/index.js#L34-L35) and [video](https://github.com/microlinkhq/metascraper/blob/b1e27626ad38d6efbc24f5104df49b2d9be3631e/packages/metascraper-video/index.js#L37-L38) packages _should_ never pass the `isMime` check if everyone follows the spec, but it doesn't hurt to leave them there.

Comment (Kikobeats) [reply packages/metascraper-iframe/src/from-twitter.js]: Thanks for that comment! I the values there. Can you double-check my last two commits?

I prefer to keep the core as restrict as possible, that will be benefit strict markup 🙂

Comment (Kikobeats) [reply packages/metascraper-iframe/src/from-twitter.js]: @nathangathright you are definitively right since I'm checking for audio/video source inside the player:

https://github.com/microlinkhq/metascraper/blob/2ff8d72be47ab4204e7753123d15f3d2805e2fee/packages/metascraper-audio/index.js#L63

Comment (nathangathright) [reply packages/metascraper-iframe/src/from-twitter.js]: Looks good to me!
